apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
    restartPolicy: Always
  type: LoadBalancer
