---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: react-deployment
 labels:
  app: react-app
spec:
 replicas: 1
 selector:
  matchLabels:
   app: react-app
 template:
  metadata: 
   labels:
    app: react-app
  spec:
   containers:
   - name: react-app
     image: fabien123/react-app:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
